/* F-SOAP · Dossiê de CIDs compatíveis por doença (campo do Plano no SOAP).
   Autoria: brain, 28/08/2026 — SUGESTÕES de CID-10 por tópico do catálogo, para a
   médica escolher ao suspeitar da doença. NÃO é decisão: o CID do atendimento é dela.
   Rotular na UI: "sugestões — conferir". Chave = id do tópico no catalogData. */
window.CIDS_COMPATIVEIS = {
  aviso: 'Sugestões de CID-10 compatíveis com a suspeita — conferir; o CID do atendimento é decisão da médica.',
  porTopico: {
    'pre-natal-rotina':[['Z34','Supervisão de gravidez normal'],['Z34.0','Supervisão de primeira gravidez normal']],
    'nauseas-vomitos-gestante':[['O21.0','Hiperêmese gravídica leve'],['O21.9','Vômitos da gravidez, NE']],
    'itu-gestante':[['O23.4','Infecção urinária na gravidez, NE'],['O23.1','Infecção da bexiga na gravidez'],['O23.0','Infecção do rim na gravidez']],
    'diabetes-gestacao':[['O24.4','Diabetes que surge na gravidez (gestacional)'],['O24.9','Diabetes na gravidez, NE']],
    'hipertensao-gestacional':[['O13','Hipertensão gestacional sem proteinúria'],['O14.9','Pré-eclâmpsia, NE'],['O10.9','Hipertensão pré-existente complicando a gravidez']],
    'anticoncepcao':[['Z30.0','Aconselhamento geral sobre anticoncepção'],['Z30.4','Supervisão do uso de anticoncepcionais']],
    'amenorreia':[['N91.0','Amenorreia primária'],['N91.1','Amenorreia secundária'],['N91.2','Amenorreia, NE']],
    'sindrome-ovarios-policisticos':[['E28.2','Síndrome dos ovários policísticos']],
    'dismenorreia':[['N94.4','Dismenorreia primária'],['N94.5','Dismenorreia secundária'],['N94.6','Dismenorreia, NE']],
    'sangramento-uterino-anormal':[['N92.1','Menstruação excessiva e frequente com ciclo irregular'],['N93.9','Sangramento anormal do útero/vagina, NE']],
    'climaterio':[['N95.1','Estados da menopausa e do climatério feminino'],['N95.9','Transtorno da menopausa e perimenopausa, NE']],
    'vaginose-bacteriana':[['N76.0','Vaginite aguda'],['N89.8','Outras afecções da vagina (vaginose)']],
    'candidiase-vulvovaginal':[['B37.3','Candidíase da vulva e da vagina'],['N77.1','Vaginite/vulvite em doença classificada em outra parte']],
    'tricomoníase':[['A59.0','Tricomoníase urogenital'],['A59.9','Tricomoníase, NE']],
    'cervicite':[['N72','Doença inflamatória do colo do útero']],
    'doenca-inflamatoria-pelvica':[['N73.9','Doença inflamatória pélvica feminina, NE'],['N70.9','Salpingite e ooforite, NE']],
    'violencia-sexual':[['T74.2','Abuso sexual'],['Z04.4','Exame após alegação de estupro/sedução']],
    'mastalgia':[['N64.4','Mastodinia']],
    'mastite-aguda':[['N61','Transtornos inflamatórios da mama (mastite)'],['O91.2','Mastite não purulenta associada ao parto']],
    'candidiase-mamaria-moniliase-lactente':[['B37.8','Candidíase de outras localizações (mamária)'],['B37.0','Estomatite por Candida (monilíase oral do lactente)']],
    'rastreio-cancer-mulher':[['Z12.3','Rastreamento de neoplasia da mama'],['Z12.4','Rastreamento de neoplasia do colo do útero'],['Z01.4','Exame ginecológico de rotina']],
    'puericultura':[['Z00.1','Exame de rotina de saúde da criança']],
    'criptorquidia':[['Q53.9','Testículo não descido, NE'],['Q53.1','Testículo não descido unilateral'],['Q53.2','Testículo não descido bilateral']],
    'hernia-umbilical-infantil':[['K42.9','Hérnia umbilical sem obstrução ou gangrena']],
    'prepucio-nao-retratil':[['N47','Hipertrofia do prepúcio, fimose e parafimose']],
    'gastroenterite-infantil':[['A09','Diarreia e gastroenterite de origem infecciosa presumível'],['A08.0','Enterite por rotavírus']],
    'amebiase-giardiase-infantil':[['A06.9','Amebíase, NE'],['A07.1','Giardíase']],
    'helmintiase-infantil':[['B77.9','Ascaridíase, NE'],['B76.9','Ancilostomíase, NE'],['B80','Oxiuríase (enterobíase)'],['B79','Tricuríase']],
    'vulvovaginite-oxiuriase-infantil':[['B80','Oxiuríase (enterobíase)'],['N76.0','Vaginite aguda']],
    'escabiose-infantil':[['B86','Escabiose']],
    'pediculose-infantil':[['B85.0','Pediculose do couro cabeludo'],['B85.2','Pediculose, NE']],
    'larva-migrans-infantil':[['B76.9','Larva migrans cutânea (ancilostomíase, NE)'],['B83.0','Larva migrans visceral (toxocaríase)']],
    'miliaria':[['L74.3','Miliária, NE'],['L74.0','Miliária rubra']],
    'estrofulo':[['L28.2','Prurigo estrófulo (urticária papular)']],
    'furunculose-infantil':[['L02.9','Abscesso cutâneo, furúnculo e antraz, NE']],
    'candidiase-oral-infantil':[['B37.0','Estomatite por Candida (sapinho)']],
    'candidiase-cutanea-infantil':[['B37.2','Candidíase da pele e das unhas']],
    'dermatite-fraldas':[['L22','Dermatite das fraldas']],
    'tinea-capitis-infantil':[['B35.0','Tinea da barba e do couro cabeludo']],
    'tinea-corporis-infantil':[['B35.4','Tinea do corpo'],['B35.6','Tinea crural'],['B35.3','Tinea dos pés']],
    'onicomicose-infantil':[['B35.1','Tinea das unhas (onicomicose)']],
    'pitiriase-versicolor-infantil':[['B36.0','Pitiríase versicolor']],
    'urticaria-dermatite-atopica-infantil':[['L50.9','Urticária, NE'],['L20.9','Dermatite atópica, NE']],
    'impetigo-infantil':[['L01.0','Impetigo']],
    'constipacao-infantil':[['K59.0','Constipação']],
    'refluxo-infantil':[['K21.9','DRGE sem esofagite'],['P92.1','Regurgitação e ruminação do recém-nascido']],
    'resfriado-comum-infantil':[['J00','Nasofaringite aguda (resfriado comum)']],
    'otite-media-aguda-infantil':[['H66.0','Otite média aguda supurativa'],['H66.9','Otite média, NE']],
    'mastoidite-infantil':[['H70.0','Mastoidite aguda']],
    'sinusite-bacteriana-infantil':[['J01.9','Sinusite aguda, NE']],
    'faringoamigdalite-infantil':[['J03.9','Amigdalite aguda, NE'],['J02.9','Faringite aguda, NE'],['A38','Escarlatina']],
    'exantemas-virais-infantis':[['B09','Infecção viral com lesões de pele/mucosas, NE'],['B08.2','Exantema súbito'],['B08.3','Eritema infeccioso'],['B01.9','Varicela sem complicação']],
    'asma-infantil':[['J45.9','Asma, NE'],['J45.0','Asma predominantemente alérgica']],
    'rinite-alergica-infantil':[['J30.4','Rinite alérgica, NE']],
    'pneumonia-infantil':[['J18.9','Pneumonia, NE'],['J15.9','Pneumonia bacteriana, NE']],
    'itu-infantil':[['N39.0','Infecção do trato urinário de localização NE']],
    'hipertensao-negros-idosos':[['I10','Hipertensão essencial (primária)']],
    'hipertensao-nefropata-diabetico-obeso':[['I10','Hipertensão essencial'],['I12.9','Doença renal hipertensiva sem insuficiência renal'],['E11.9','Diabetes tipo 2 sem complicações'],['E66.9','Obesidade, NE']],
    'hipertensao-branco-jovem':[['I10','Hipertensão essencial (primária)']],
    'hipertensao-ic-dac':[['I10','Hipertensão essencial'],['I11.0','Cardiopatia hipertensiva com insuficiência cardíaca'],['I25.9','Doença isquêmica crônica do coração, NE']],
    'dislipidemia-diabetes':[['E78.5','Hiperlipidemia, NE'],['E78.2','Hiperlipidemia mista'],['E11.9','Diabetes tipo 2 sem complicações']],
    'dislipidemia-alto-risco':[['E78.0','Hipercolesterolemia pura'],['E78.5','Hiperlipidemia, NE']],
    'dislipidemia-aterosclerose-significativa':[['E78.0','Hipercolesterolemia pura'],['I70.9','Aterosclerose generalizada e NE'],['I25.1','Doença aterosclerótica do coração']],
    'hipertrigliceridemia':[['E78.1','Hipertrigliceridemia pura']],
    'diabetes-mellitus-tipo-2':[['E11.9','Diabetes tipo 2 sem complicações'],['E11.8','Diabetes tipo 2 com complicações NE']],
    'neuropatia-periferica':[['G62.9','Polineuropatia, NE'],['E11.4','Diabetes tipo 2 com complicações neurológicas']],
    'pe-diabetico':[['E11.5','Diabetes tipo 2 com complicações circulatórias periféricas'],['E11.7','Diabetes tipo 2 com complicações múltiplas'],['L97','Úlcera de membro inferior NCOP']],
    'anemia-macrocitica':[['D53.1','Outras anemias megaloblásticas NCOP'],['D51.9','Anemia por deficiência de vitamina B12, NE'],['D52.9','Anemia por deficiência de folato, NE']],
    'anemia-ferropriva':[['D50.9','Anemia por deficiência de ferro, NE'],['D50.8','Outras anemias ferroprivas']],
    'osteoporose':[['M81.0','Osteoporose pós-menopáusica sem fratura'],['M81.9','Osteoporose sem fratura, NE']],
    'osteoartrite':[['M19.9','Artrose, NE'],['M17.9','Gonartrose, NE'],['M16.9','Coxartrose, NE'],['M15.9','Poliartrose, NE']],
    'hipotireoidismo':[['E03.9','Hipotireoidismo, NE']],
    'hipertireoidismo':[['E05.9','Tireotoxicose, NE'],['E05.0','Tireotoxicose com bócio difuso (Graves)']],
    'abscesso-celulite':[['L02.9','Abscesso cutâneo, furúnculo e antraz, NE'],['L03.9','Celulite, NE']],
    'erisipela':[['A46','Erisipela']],
    'impetigo-adulto':[['L01.0','Impetigo']],
    'cistite-adulto':[['N30.0','Cistite aguda'],['N39.0','Infecção do trato urinário de localização NE']],
    'prostatite':[['N41.0','Prostatite aguda'],['N41.1','Prostatite crônica'],['N41.9','Doença inflamatória da próstata, NE']],
    'hiperplasia-prostatica-benigna':[['N40','Hiperplasia da próstata']],
    'pneumonia-comunitaria-adulto':[['J18.9','Pneumonia, NE'],['J15.9','Pneumonia bacteriana, NE'],['J13','Pneumonia por Streptococcus pneumoniae']],
    'asma-dpoc-adulto':[['J45.9','Asma, NE'],['J44.9','DPOC, NE'],['J44.1','DPOC com exacerbação aguda, NE']],
    'rinite-alergica-adulto':[['J30.4','Rinite alérgica, NE']],
    'rinossinusite-adulto':[['J01.9','Sinusite aguda, NE'],['J32.9','Sinusite crônica, NE']],
    'tuberculose-pulmonar':[['A15.0','TB pulmonar com confirmação por baciloscopia'],['A16.2','TB pulmonar sem confirmação bacteriológica/histológica']],
    'infeccao-latente-tuberculose':[['Z20.1','Contato/exposição à tuberculose'],['R76.1','Reação anormal ao teste tuberculínico']],
    'hanseniase':[['A30.9','Hanseníase, NE']],
    'tinea-capitis-adulto':[['B35.0','Tinea da barba e do couro cabeludo']],
    'tinea-corporis-adulto':[['B35.4','Tinea do corpo'],['B35.6','Tinea crural'],['B35.3','Tinea dos pés']],
    'onicomicose-adulto':[['B35.1','Tinea das unhas (onicomicose)']],
    'candidiase-cutanea-adulto':[['B37.2','Candidíase da pele e das unhas']],
    'pitiriase-versicolor-adulto':[['B36.0','Pitiríase versicolor']],
    'escabiose-adulto':[['B86','Escabiose']],
    'pediculose-adulto':[['B85.0','Pediculose do couro cabeludo'],['B85.3','Ftiríase (pediculose pubiana)']],
    'parasitose-intestinal-adulto':[['B82.9','Parasitose intestinal, NE'],['A06.9','Amebíase, NE'],['A07.1','Giardíase']],
    'acne':[['L70.0','Acne vulgar'],['L70.9','Acne, NE']],
    'afta-oral':[['K12.0','Aftas bucais recidivantes']],
    'verruga-vulgar':[['B07','Verrugas de origem viral']],
    'migranea':[['G43.9','Enxaqueca, NE'],['G43.0','Enxaqueca sem aura'],['G43.1','Enxaqueca com aura']],
    'dorsalgia-discopatia':[['M54.5','Dor lombar baixa'],['M54.4','Lumbago com ciática'],['M51.9','Transtorno de disco intervertebral, NE'],['M54.9','Dorsalgia, NE']],
    'fibromialgia':[['M79.7','Fibromialgia']],
    'vertigem':[['R42','Tontura e instabilidade'],['H81.1','Vertigem paroxística benigna'],['H81.9','Transtorno da função vestibular, NE']],
    'gastroenterite-adulto':[['A09','Diarreia e gastroenterite de origem infecciosa presumível'],['K52.9','Gastroenterite e colite não infecciosas, NE']],
    'constipacao-adulto':[['K59.0','Constipação']],
    'drge-adulto':[['K21.9','DRGE sem esofagite'],['K21.0','DRGE com esofagite']],
    'gastrite-dup':[['K29.7','Gastrite, NE'],['K25.9','Úlcera gástrica, NE'],['K26.9','Úlcera duodenal, NE'],['B98.0','Helicobacter pylori como causa de doença']],
    'conjuntivite':[['H10.9','Conjuntivite, NE'],['H10.3','Conjuntivite aguda, NE']],
    'hordeolo':[['H00.0','Hordéolo e outras inflamações profundas da pálpebra']],
    'otite-media-aguda-adulto':[['H66.0','Otite média aguda supurativa'],['H66.9','Otite média, NE']],
    'otite-externa':[['H60.9','Otite externa, NE'],['H60.0','Abscesso da orelha externa']],
    'rolha-cerume':[['H61.2','Cerume impactado']],
    'faringoamigdalite-adulto':[['J03.9','Amigdalite aguda, NE'],['J02.9','Faringite aguda, NE']],
    'gota':[['M10.9','Gota, NE'],['M10.0','Gota idiopática']],
    'insuficiencia-venosa-cronica':[['I87.2','Insuficiência venosa (crônica) (periférica)'],['I83.9','Varizes de MMII sem úlcera ou inflamação'],['I83.0','Varizes de MMII com úlcera']],
    'herpes-mucocutaneo':[['B00.9','Infecção pelo vírus do herpes, NE'],['B00.1','Dermatite vesicular pelo vírus do herpes']],
    'herpes-zoster':[['B02.9','Herpes-zóster sem complicação']],
    'herpes-genital':[['A60.0','Infecção herpética dos órgãos genitais/trato geniturinário'],['A60.9','Infecção anogenital herpética, NE']],
    'cancro-mole':[['A57','Cancro mole']],
    'sifilis':[['A53.9','Sífilis, NE'],['A51.0','Sífilis genital primária'],['A53.0','Sífilis latente NE']],
    'linfogranuloma-venereo':[['A55','Linfogranuloma venéreo por clamídia']],
    'rastreio-cancer-colorretal':[['Z12.1','Rastreamento de neoplasia do intestino (colorretal)']],
    'covid-19':[['U07.1','COVID-19 confirmada'],['U07.2','COVID-19 suspeita/não confirmada']]
  }
};
