/* F-H · Dossiê Orquestrador — dados da farmácia da unidade.
   Fonte fiel: "Cópia de Lista de medicamentos farmacia Clínica do Orquestrador.pdf"
   (transcrita do PDF ORIGINAL em 28/08/2026, com as categorias color-coded e os
   itens RISCADOS do original preservados — riscado = provável falta/descontinuado,
   confirmar na unidade). Nome literal da lista; correção de grafia vai em `obs`. */
window.FARMACIA_CSF = {
  unidade: 'Clínica do Orquestrador',
  fonte: 'Lista de Medicamentos Farmácia Clínica do Orquestrador (PDF)',
  transcritoEm: '2026-08-28',
  notaRiscados: 'Itens riscados na lista original aparecem com o selo "riscado na lista" — provável falta; confirme na farmácia antes de contar com eles.',
  categorias: ['Analgésicos','Anti-inflamatórios','Antimicrobianos','Antialérgicos','Controlados','Digestivo','Injetáveis','Respiratório','Saúde da mulher','Uso contínuo/outros'],
  itens: [
    {nome:'Acetato Betametasona + Fosfato Dissódico Betametasona (Beta-Long) 3+3mg/ml susp Inj 1 ml', cat:'Injetáveis'},
    {nome:'Acetofenida + Estradiol 150 + 10mg/ml Sol Inj 1 ml', cat:'Saúde da mulher'},
    {nome:'Aciclovir 200 mg cp', cat:'Antimicrobianos'},
    {nome:'Ácido Acetilsalicílico 100mg cp', cat:'Uso contínuo/outros', riscado:true},
    {nome:'Ácido Fólico 5 mg cp', cat:'Saúde da mulher', riscado:true},
    {nome:'Ácido Fólico 0,2mg/ml sol oral gts 30 ml (0,01mg/Gota - 20 Gotas 1 ml)', cat:'Saúde da mulher'},
    {nome:'Ácido Valpróico 250 mg/5 ml Xarope fr 100ml', cat:'Controlados'},
    {nome:'Ácido Valpróico 250mg cp', cat:'Controlados'},
    {nome:'Ácido Valpróico 500mg cp', cat:'Controlados'},
    {nome:'Albendazol 400 mg comprimido', cat:'Uso contínuo/outros'},
    {nome:'Albendazol 40mg/ml suspensão oral 10 ml', cat:'Uso contínuo/outros', riscado:true},
    {nome:'Alendronato Sódico 70 mg cp', cat:'Uso contínuo/outros'},
    {nome:'Alopurinol 100 mg cp', cat:'Uso contínuo/outros'},
    {nome:'Alopurinol 300 mg cp', cat:'Uso contínuo/outros'},
    {nome:'Amiodarona 200 mg cp', cat:'Uso contínuo/outros'},
    {nome:'Amitriptilina 25mg cp', cat:'Controlados'},
    {nome:'Amoxicilina + Clavulanato 250/62,5mg/5ml susp fr 75 ml', cat:'Antimicrobianos'},
    {nome:'Amoxicilina + Clavulanato 400/57mg/5ml susp fr 70 ml', cat:'Antimicrobianos', riscado:true},
    {nome:'Amoxicilina + Clavulanato 500/125mg cp', cat:'Antimicrobianos'},
    {nome:'Amoxicilina 500mg Cap.', cat:'Antimicrobianos'},
    {nome:'Anlodipino 5mg cp', cat:'Uso contínuo/outros'},
    {nome:'Atenolol 50 mg cp', cat:'Uso contínuo/outros'},
    {nome:'Azitromicina 200mg/5ml pó susp fr 900 mg', cat:'Antimicrobianos', riscado:true},
    {nome:'Azitromicina 500mg cp', cat:'Antimicrobianos'},
    {nome:'Baclofeno 10 mg cp', cat:'Uso contínuo/outros'},
    {nome:'Beclometasona 200mcg Aer Oral fr 200 Doses', cat:'Respiratório'},
    {nome:'Beclometasona 50mcg Aer Oral fr 200 Doses', cat:'Respiratório'},
    {nome:'Biperideno 2 mg cp', cat:'Controlados'},
    {nome:'Bromoprida 10mg cp', cat:'Digestivo'},
    {nome:'Budesonida 50 mcg susp Spray Nasal 120 Doses', cat:'Respiratório'},
    {nome:'Budesonida 32mcg susp Spray Nasal 120 Doses', cat:'Respiratório'},
    {nome:'Carbamazepina 200mg cp', cat:'Controlados'},
    {nome:'Carbonato de Cálcio 1250 mg (500mg Cálcio) + Vitamina D3 400 UI cp', cat:'Uso contínuo/outros'},
    {nome:'Carbonato de Lítio 300mg cp', cat:'Controlados'},
    {nome:'Cefalexina 250mg/5ml susp fr 100ml', cat:'Antimicrobianos'},
    {nome:'Cefalexina 500mg Cap', cat:'Antimicrobianos'},
    {nome:'Cetoconazol 20 mg/g creme derm tubo 30g', cat:'Antimicrobianos'},
    {nome:'Citalopram 20 mg cp', cat:'Controlados'},
    {nome:'Claritromicina 500 mg cp', cat:'Antimicrobianos'},
    {nome:'Clonazepam 2 mg comprimido', cat:'Controlados'},
    {nome:'Clonazepam 2,5mg/ml sol oral gts fr 20 ml (25 gotas 1 ml)', cat:'Controlados'},
    {nome:'Cloreto de Sódio 0,9% Inj 100 ml', cat:'Injetáveis'},
    {nome:'Cloreto de Sódio 0,9% Inj 500 ml', cat:'Injetáveis'},
    {nome:'Clorpromazina 100mg cp', cat:'Controlados'},
    {nome:'Complexo B Inj 2 ml', cat:'Injetáveis'},
    {nome:'Dexametasona 0,1 mg/ml Elixir 100 ml', cat:'Anti-inflamatórios'},
    {nome:'Dexametasona Inj 4mg/ml 2,5 ml', cat:'Injetáveis'},
    {nome:'Dexclorfeniramina 2mg cp', cat:'Antialérgicos'},
    {nome:'Dexclorfeniramina sol oral 0,04% fr 100ml', cat:'Antialérgicos'},
    {nome:'Diazepam 10mg cp', cat:'Controlados'},
    {nome:'Diazepam 5mg/ml Inj 2ml', cat:'Controlados'},
    {nome:'Diclofenaco Sódico 25mg/ml Inj', cat:'Injetáveis'},
    {nome:'Dipirona 500mg cp', cat:'Analgésicos'},
    {nome:'Dipirona 500mg/ml gts fr 10 ml (25mg/Gota - 20 Gotas 1 ml)', cat:'Analgésicos'},
    {nome:'Dipirona 500mg/ml Sol. Inj 2 ml', cat:'Injetáveis'},
    {nome:'Domperidona 1 mg/ml susp Oral 100ml', cat:'Digestivo', riscado:true},
    {nome:'Doxazosina 2 mg cp', cat:'Uso contínuo/outros'},
    {nome:'Enalapril 10 mg cp', cat:'Uso contínuo/outros'},
    {nome:'Enalapril 20 mg cp', cat:'Uso contínuo/outros'},
    {nome:'Escopolamina 20mg/ml Inj 1ml', cat:'Injetáveis'},
    {nome:'Espironolactona 25 mg cp', cat:'Uso contínuo/outros'},
    {nome:'Fenitoína 100mg cp', cat:'Controlados'},
    {nome:'Fenobarbital 100mg cp', cat:'Controlados'},
    {nome:'Fluconazol 150mg Cap.', cat:'Antimicrobianos'},
    {nome:'Fluoxetina 20mg Cap', cat:'Controlados'},
    {nome:'Furosemida 10mg/ml Sol Inj 2 ml', cat:'Injetáveis'},
    {nome:'Furosemida 40 mg comprimido', cat:'Uso contínuo/outros'},
    {nome:'Gliclazida 30 mg cp Lib Prol', cat:'Uso contínuo/outros', riscado:true},
    {nome:'Gliclazida 60 mg cp Lib Prol', cat:'Uso contínuo/outros', riscado:true},
    {nome:'Glicose 50% Inj 10 ml', cat:'Injetáveis'},
    {nome:'Haloperidol 5 mg/ml Inj 1 ml', cat:'Controlados'},
    {nome:'Haloperidol 5mg cp', cat:'Controlados'},
    {nome:'Hidroclorotiazida 25 mg cp', cat:'Uso contínuo/outros'},
    {nome:'Hidrocortisona 500mg pó Sol Inj.', cat:'Injetáveis'},
    {nome:'Hidróxido de Alumínio 60mg/ml susp Oral fr 100 ml', cat:'Digestivo'},
    {nome:'Ibuprofeno 50mg/ml susp gts fr 30ml (5mg/Gota - 10 Gotas 1 ml)', cat:'Analgésicos'},
    {nome:'Ibuprofeno 300 mg cp', cat:'Analgésicos'},
    {nome:'Ibuprofeno 600 mg cp', cat:'Analgésicos'},
    {nome:'Insulina NPH 100UI/ml tubete 3ml Para Caneta', cat:'Uso contínuo/outros'},
    {nome:'Insulina NPH 100UI/ml fr 10ml', cat:'Uso contínuo/outros'},
    {nome:'Insulina Regular 100UI/ml tubete 3ml Para Caneta', cat:'Uso contínuo/outros'},
    {nome:'Insulina Regular 100UI/ml fr 10ml', cat:'Uso contínuo/outros'},
    {nome:'Lactulose 667mg/ml fr 120 ml', cat:'Digestivo', riscado:true},
    {nome:'Levomepromazina 25mg cp', cat:'Controlados'},
    {nome:'Levonorgestrel + Etinilestradiol 0,15mg + 0,03mg cp', cat:'Saúde da mulher'},
    {nome:'Levotiroxina 100mcg cp', cat:'Uso contínuo/outros'},
    {nome:'Levotiroxina 25mcg cp', cat:'Uso contínuo/outros'},
    {nome:'Levotiroxina 50mcg cp', cat:'Uso contínuo/outros'},
    {nome:'Loratadina 10mg cp', cat:'Antialérgicos'},
    {nome:'Loratadina 1mg/ml Xpe fr 100ml', cat:'Antialérgicos'},
    {nome:'Losartana 50mg cp', cat:'Uso contínuo/outros', riscado:true},
    {nome:'Medroxiprogesterona 150 mg/ml susp Inj 1 ml', cat:'Saúde da mulher'},
    {nome:'Metformina 850 mg cp', cat:'Uso contínuo/outros'},
    {nome:'Metoprolol succinato 50 mg cp', cat:'Uso contínuo/outros'},
    {nome:'Metoprolol succinato 100 mg cp', cat:'Uso contínuo/outros'},
    {nome:'Metronidazol 100mg/g Gel Vag. 50 g', cat:'Antimicrobianos'},
    {nome:'Metronidazol 250mg cp', cat:'Antimicrobianos'},
    {nome:'Metronidazol 400mg cp', cat:'Antimicrobianos'},
    {nome:'Miconazol 2% Creme Derm 28g', cat:'Antimicrobianos'},
    {nome:'Nimesulida 100mg cp.', cat:'Analgésicos'},
    {nome:'Nortriptilina 25mg cp', cat:'Controlados'},
    {nome:'Noretisterona + Estradiol 50 + 5mg/ml Inj 1ml', cat:'Saúde da mulher', riscado:true},
    {nome:'Omeprazol 20mg Cap', cat:'Digestivo'},
    {nome:'Ondansetrona 4 mg cp orodispersível', cat:'Digestivo'},
    {nome:'Ondansetrona 8 mg cp', cat:'Digestivo', obs:'não consta no PDF da lista — tem na unidade, confirmado pela casa (28/08)'},
    {nome:'Paracetamol 200mg/ml gts fr 15ml', cat:'Analgésicos'},
    {nome:'Paracetamol 500mg cp', cat:'Analgésicos'},
    {nome:'Paracetamol + Codeína 500mg + 30 mg cp cartela 12 cp', cat:'Analgésicos'},
    {nome:'Permetrina 10 mg/ml (1%) loção capilar 60 ml', cat:'Uso contínuo/outros'},
    {nome:'Permetrina 50 mg/ml (5%) loção cremosa 60 ml', cat:'Uso contínuo/outros'},
    {nome:'Prednisolona 3mg/ml sol oral 60 ml', cat:'Anti-inflamatórios'},
    {nome:'Prednisona 5mg cp', cat:'Anti-inflamatórios'},
    {nome:'Prednisona 20 mg cp', cat:'Anti-inflamatórios', obs:'grafada "Prednsona" na lista original'},
    {nome:'Prometazina 25mg cp', cat:'Antialérgicos'},
    {nome:'Prometazina 25mg/ml Inj 2 ml.', cat:'Injetáveis'},
    {nome:'Propranolol 40 mg cp', cat:'Uso contínuo/outros'},
    {nome:'Sais de Reidratação Oral', cat:'Digestivo'},
    {nome:'Sertralina 50mg cp', cat:'Controlados'},
    {nome:'Sinvastatina 10mg cp', cat:'Uso contínuo/outros'},
    {nome:'Sinvastatina 20mg cp', cat:'Uso contínuo/outros', riscado:true},
    {nome:'Sinvastatina 40mg cp', cat:'Uso contínuo/outros'},
    {nome:'Sulfametoxazol 400mg + Trimetoprima 80 mg cp', cat:'Antimicrobianos'},
    {nome:'Sulfametoxazol + Trimetoprima 200+40mg/5ml susp. fr 100ml', cat:'Antimicrobianos'},
    {nome:'Sulfato Ferroso (40 mg Ferro Elementar) cp', cat:'Uso contínuo/outros'},
    {nome:'Sulfato Ferroso 25mg/ml (5mg/ml Ferro Elementar) Xarope', cat:'Uso contínuo/outros'},
    {nome:'Tramadol 50mg/ml Sol Inj 2 ml', cat:'Controlados'}
  ]
};
